# For more information: https://laravel.com/docs/sail
# This file create the production environment.
version: '3'
services:
    webserver:
        build:
            context: ./docker/
            dockerfile: ./apache/Dockerfile
        image: 'custom.laravel/laravel-apache'
        container_name: webserver
        ports:
            - "443:443"
        volumes:
            - '.:${WEB_ROOT}'
            - '${PROD_CERT_CRT_FULLPATH}:/etc/ssl/certs/cert.crt'
            - '${PROD_CERT_KEY_FULLPATH}:/etc/ssl/private/cert.key'
        networks:
            - laravel-network
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            TZ: 'Europe/Zurich'
        volumes:
            - 'mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - laravel-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

networks:
    laravel-network:
        driver: bridge
volumes:
    mysql:
        driver: local
